export const ERROR = {
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  EMAIL_ID_EXISTS: "EMAIL_ID_EXISTS",
  UNAUTHORIZED: "UNAUTHORIZED",
};

export const SUCCESS = {
  CASE_CREATE_SUCCESSFUL: "CASE_CREATE_SUCCESSFUL",
  CASE_UPDATE_SUCCESSFUL: "CASE_UPDATE_SUCCESSFUL",
  CASE_REMOVE_SUCCESSFUL: "CASE_REMOVE_SUCCESSFUL",
  CLIENT_CREATE_SUCCESSFUL: "CLIENT_CREATED_SUCCESSFUL",
  CLIENT_UPDATE_SUCCESSFUL: "CLIENT_UPDATE_SUCCESSFUL",
  CLIENT_REMOVE_SUCCESSFUL: "CLIENT_REMOVE_SUCCESSFUL",
  LAWYER_CREATE_SUCCESSFUL: "LAWYER_CREATED_SUCCESSFUL",
  LAWYER_UPDATE_SUCCESSFUL: "LAWYER_UPDATED_SUCCESSFUL",
  LAWYER_REMOVE_SUCCESSFUL: "LAWYER_REMOVE_SUCCESSFUL",
  CLIENT_CASE_FETCH_SUCCESSFUL: "CLIENT_CASE_FETCH_SUCCESSFUL",
  LAWYER_CASE_FETCH_SUCCESSFUL: "LAWYER_CASE_FETCH_SUCCESSFUL",
  LAWYER_REQUEST_SUCCESSFUL: "LAWYER_REQUEST_SUCCESSFUL",
  CLIENT_CASE_REQUEST_IGNORE_SUCCESSFUL:
    "CLIENT_CASE_REQUEST_IGNORE_SUCCESSFUL",
  CLIENT_CASE_ACCEPT_SUCCESSFUL: "CLIENT_CASE_ACCEPT_SUCCESSFUL",
  CLIENT_LOGIN_SUCCESSFUL: "CLIENT_LOGIN_SUCCESSFUL",
  LAWYER_LOGIN_SUCCESSFUL: "LAWYER_LOGIN_SUCCESSFUL",
  TOKEN_VALIDATION_SUCCESSFUL: "TOKEN_VALIDATION_SUCCESSFUL",
};
